// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image12":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image13":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image14":return img`
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image15":return img`
..ff.......cc...
..fbff...fcbc...
..fbbcfffbbbc...
...fbbccbbbc....
....fbcbbddc....
.....fbbddc.....
.....fcbfc......
.....fccf.......
....ccccf.......
...cbccccf......
...cdccccf......
..cdbcccccf.....
..cdccccccf.....
.cddccccccf.....
ffddcccbbbcf..ff
fbfdccbbbbbfffbf
fbbfcbbbbbbccbbf
fdbbbbbccbbcbbdc
fbdbbbbbbcbcbddc
.fbbbbbccbbccdc.
.cfc11bbbcbccc..
.c111111bbbcf...
.c111c1ffbbf....
.c11cc1ffbbf....
.c1c1311bbbf....
..f33311bbbf....
..f31c11bbbf....
...fcc11bbbf....
....fc1bbbf.....
.....fbbcbf.....
......fbbf......
.......fff......
`;
            case "image16":return img`
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image17":return img`
..ff.......cc...
..fbff...fcbc...
..fbbcfffbbbc...
...fbbccbbbc....
....fbcbbddc....
.....fbbddc.....
.....fcbfc......
.....fccf.......
....ccccf.......
...cbccccf......
...cdccccf......
..cdbcccccf.....
..cdccccccf.....
.cddccccccf.....
ffddcccbbbcf..ff
fbfdccbbbbbfffbf
fbbfcbbbbbbccbbf
fdbbbbbccbbcbbdc
fbdbbbbbbcbcbddc
.fbbbbbccbbccdc.
.cfc11bbbcbccc..
.c111111bbbcf...
.c111c1ffbbf....
.c11cc1ffbbf....
.c1c1311bbbf....
..f33311bbbf....
..f31c11bbbf....
...fcc11bbbf....
....fc1bbbf.....
.....fbbcbf.....
......fbbf......
.......fff......
`;
            case "image18":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image19":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image20":return img`
................
................
................
................
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image21":return img`
................
................
................
................
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image22":return img`
. . . . . . . . . . b 5 b . . . 
. . . . . . . . . b 5 b . . . . 
. . . . . . b b b b b b . . . . 
. . . . . b b 5 5 5 5 5 b . . . 
. . . . b b 5 d 1 f 5 d 4 c . . 
. . . . b 5 5 1 f f d d 4 4 4 b 
. . . . b 5 5 d f b 4 4 4 4 b . 
. . . b d 5 5 5 5 4 4 4 4 b . . 
. . b d d 5 5 5 5 5 5 5 5 b . . 
. b d d d d 5 5 5 5 5 5 5 5 b . 
b d d d b b b 5 5 5 5 5 5 5 b . 
c d d b 5 5 d c 5 5 5 5 5 5 b . 
c b b d 5 d c d 5 5 5 5 5 5 b . 
. b 5 5 b c d d 5 5 5 5 5 d b . 
b b c c c d d d d 5 5 5 b b . . 
. . . c c c c c c c c b b . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "walkRight":
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . f f e e e e f 2 f . . . . 
. . f f e e e e f 2 2 2 f . . . 
. . f e e e f f e e e e f . . . 
. . f f f f e e 2 2 2 2 e f . . 
. . f e 2 2 2 f f f f e 2 f . . 
. f f f f f f f e e e f f f . . 
. f f e 4 4 e b f 4 4 e e f . . 
. f e e 4 d 4 1 f d d e f . . . 
. . f e e e e e d d d f . . . . 
. . . . f 4 d d e 4 e f . . . . 
. . . . f e d d e 2 2 f . . . . 
. . . f f f e e f 5 5 f f . . . 
. . . f f f f f f f f f f . . . 
. . . . f f . . . f f f . . . . 
`, img`
. . . . . f f f f f f . . . . . 
. . . f f e e e e f 2 f . . . . 
. . f f e e e e f 2 2 2 f . . . 
. . f e e e f f e e e e f . . . 
. . f f f f e e 2 2 2 2 e f . . 
. . f e 2 2 2 f f f f e 2 f . . 
. f f f f f f f e e e f f f . . 
. f f e 4 4 e b f 4 4 e e f . . 
. f e e 4 d 4 1 f d d e f f . . 
. . f e e e 4 d d d d f d d f . 
. . . f f e e 4 e e e f b b f . 
. . . . f 2 2 2 4 d d e b b f . 
. . . . e 2 2 2 e d d e b f . . 
. . . . f 4 4 4 f e e f f . . . 
. . . . . f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . f f e e e e f 2 f . . . . 
. . f f e e e e f 2 2 2 f . . . 
. . f e e e f f e e e e f . . . 
. . f f f f e e 2 2 2 2 e f . . 
. . f e 2 2 2 f f f f e 2 f . . 
. f f f f f f f e e e f f f . . 
. f f e 4 4 e b f 4 4 e e f . . 
. f e e 4 d 4 1 f d d e f . . . 
. . f e e e e e d d d f . . . . 
. . . . f 4 d d e 4 e f . . . . 
. . . . f e d d e 2 2 f . . . . 
. . . f f f e e f 5 5 f f . . . 
. . . f f f f f f f f f f . . . 
. . . . f f . . . f f f . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . f f e e e e f 2 f . . . . 
. . f f e e e e f 2 2 2 f . . . 
. . f e e e f f e e e e f . . . 
. . f f f f e e 2 2 2 2 e f . . 
. . f e 2 2 2 f f f f e 2 f . . 
. f f f f f f f e e e f f f . . 
. f f e 4 4 e b f 4 4 e e f . . 
. f e e 4 d 4 1 f d d e f f . . 
. . f e e e 4 d d d d f d d f . 
. . . . f e e 4 e e e f b b f . 
. . . . f 2 2 2 4 d d e b b f . 
. . . f f 4 4 4 e d d e b f . . 
. . . f f f f f f e e f f . . . 
. . . . f f . . . f f f . . . . 
`];
            case "walkLeft":
            case "anim2":return [img`
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e e f f . . . . 
. . . f 2 2 2 e d d 4 . . . . . 
. . . f 2 2 2 e d d e . . . . . 
. . . f 5 5 4 f e e f . . . . . 
. . . . f f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d e e e e e f . . . 
. . . f e 4 e d d 4 f . . . . . 
. . . f 2 2 e d d e f . . . . . 
. . f f 5 5 f e e f f f . . . . 
. . f f f f f f f f f f . . . . 
. . . f f f . . . f f . . . . . 
`, img`
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e e f f . . . . 
. . . f 2 2 2 e d d 4 . . . . . 
. . . f 2 2 2 e d d e . . . . . 
. . . f 5 5 4 f e e f . . . . . 
. . . . f f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e d d 4 . . . . 
. . . f 2 2 2 2 e d d e . . . . 
. . f f 5 5 4 4 f e e f . . . . 
. . f f f f f f f f f f . . . . 
. . . f f f . . . f f . . . . . 
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
