// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":return img`
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image2":return img`
..ff.......cc...
..fbff...fcbc...
..fbbcfffbbbc...
...fbbccbbbc....
....fbcbbddc....
.....fbbddc.....
.....fcbfc......
.....fccf.......
....ccccf.......
...cbccccf......
...cdccccf......
..cdbcccccf.....
..cdccccccf.....
.cddccccccf.....
ffddcccbbbcf..ff
fbfdccbbbbbfffbf
fbbfcbbbbbbccbbf
fdbbbbbccbbcbbdc
fbdbbbbbbcbcbddc
.fbbbbbccbbccdc.
.cfc11bbbcbccc..
.c111111bbbcf...
.c111c1ffbbf....
.c11cc1ffbbf....
.c1c1311bbbf....
..f33311bbbf....
..f31c11bbbf....
...fcc11bbbf....
....fc1bbbf.....
.....fbbcbf.....
......fbbf......
.......fff......
`;
            case "image3":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image4":return img`
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image5":return img`
..ff.......cc...
..fbff...fcbc...
..fbbcfffbbbc...
...fbbccbbbc....
....fbcbbddc....
.....fbbddc.....
.....fcbfc......
.....fccf.......
....ccccf.......
...cbccccf......
...cdccccf......
..cdbcccccf.....
..cdccccccf.....
.cddccccccf.....
ffddcccbbbcf..ff
fbfdccbbbbbfffbf
fbbfcbbbbbbccbbf
fdbbbbbccbbcbbdc
fbdbbbbbbcbcbddc
.fbbbbbccbbccdc.
.cfc11bbbcbccc..
.c111111bbbcf...
.c111c1ffbbf....
.c11cc1ffbbf....
.c1c1311bbbf....
..f33311bbbf....
..f31c11bbbf....
...fcc11bbbf....
....fc1bbbf.....
.....fbbcbf.....
......fbbf......
.......fff......
`;
            case "image6":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image7":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image8":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image9":return img`
................
................
................
................
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image10":return img`
................
................
................
................
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image11":return img`
. . . . . . . . . . b 5 b . . . 
. . . . . . . . . b 5 b . . . . 
. . . . . . b b b b b b . . . . 
. . . . . b b 5 5 5 5 5 b . . . 
. . . . b b 5 d 1 f 5 d 4 c . . 
. . . . b 5 5 1 f f d d 4 4 4 b 
. . . . b 5 5 d f b 4 4 4 4 b . 
. . . b d 5 5 5 5 4 4 4 4 b . . 
. . b d d 5 5 5 5 5 5 5 5 b . . 
. b d d d d 5 5 5 5 5 5 5 5 b . 
b d d d b b b 5 5 5 5 5 5 5 b . 
c d d b 5 5 d c 5 5 5 5 5 5 b . 
c b b d 5 d c d 5 5 5 5 5 5 b . 
. b 5 5 b c d d 5 5 5 5 5 d b . 
b b c c c d d d d 5 5 5 b b . . 
. . . c c c c c c c c b b . . . 
`;
            case "image12":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image13":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image14":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image15":return img`
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image16":return img`
..ff.......cc...
..fbff...fcbc...
..fbbcfffbbbc...
...fbbccbbbc....
....fbcbbddc....
.....fbbddc.....
.....fcbfc......
.....fccf.......
....ccccf.......
...cbccccf......
...cdccccf......
..cdbcccccf.....
..cdccccccf.....
.cddccccccf.....
ffddcccbbbcf..ff
fbfdccbbbbbfffbf
fbbfcbbbbbbccbbf
fdbbbbbccbbcbbdc
fbdbbbbbbcbcbddc
.fbbbbbccbbccdc.
.cfc11bbbcbccc..
.c111111bbbcf...
.c111c1ffbbf....
.c11cc1ffbbf....
.c1c1311bbbf....
..f33311bbbf....
..f31c11bbbf....
...fcc11bbbf....
....fc1bbbf.....
.....fbbcbf.....
......fbbf......
.......fff......
`;
            case "image17":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image18":return img`
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image19":return img`
..ff.......cc...
..fbff...fcbc...
..fbbcfffbbbc...
...fbbccbbbc....
....fbcbbddc....
.....fbbddc.....
.....fcbfc......
.....fccf.......
....ccccf.......
...cbccccf......
...cdccccf......
..cdbcccccf.....
..cdccccccf.....
.cddccccccf.....
ffddcccbbbcf..ff
fbfdccbbbbbfffbf
fbbfcbbbbbbccbbf
fdbbbbbccbbcbbdc
fbdbbbbbbcbcbddc
.fbbbbbccbbccdc.
.cfc11bbbcbccc..
.c111111bbbcf...
.c111c1ffbbf....
.c11cc1ffbbf....
.c1c1311bbbf....
..f33311bbbf....
..f31c11bbbf....
...fcc11bbbf....
....fc1bbbf.....
.....fbbcbf.....
......fbbf......
.......fff......
`;
            case "image20":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image21":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image22":return img`
................
................
................
................
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image23":return img`
................
................
................
................
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image24":return img`
. . . . . . . . . . b 5 b . . . 
. . . . . . . . . b 5 b . . . . 
. . . . . . b b b b b b . . . . 
. . . . . b b 5 5 5 5 5 b . . . 
. . . . b b 5 d 1 f 5 d 4 c . . 
. . . . b 5 5 1 f f d d 4 4 4 b 
. . . . b 5 5 d f b 4 4 4 4 b . 
. . . b d 5 5 5 5 4 4 4 4 b . . 
. . b d d 5 5 5 5 5 5 5 5 b . . 
. b d d d d 5 5 5 5 5 5 5 5 b . 
b d d d b b b 5 5 5 5 5 5 5 b . 
c d d b 5 5 d c 5 5 5 5 5 5 b . 
c b b d 5 d c d 5 5 5 5 5 5 b . 
. b 5 5 b c d d 5 5 5 5 5 d b . 
b b c c c d d d d 5 5 5 b b . . 
. . . c c c c c c c c b b . . . 
`;
            case "image25":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image26":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image27":return img`
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image28":return img`
..ff.......cc...
..fbff...fcbc...
..fbbcfffbbbc...
...fbbccbbbc....
....fbcbbddc....
.....fbbddc.....
.....fcbfc......
.....fccf.......
....ccccf.......
...cbccccf......
...cdccccf......
..cdbcccccf.....
..cdccccccf.....
.cddccccccf.....
ffddcccbbbcf..ff
fbfdccbbbbbfffbf
fbbfcbbbbbbccbbf
fdbbbbbccbbcbbdc
fbdbbbbbbcbcbddc
.fbbbbbccbbccdc.
.cfc11bbbcbccc..
.c111111bbbcf...
.c111c1ffbbf....
.c11cc1ffbbf....
.c1c1311bbbf....
..f33311bbbf....
..f31c11bbbf....
...fcc11bbbf....
....fc1bbbf.....
.....fbbcbf.....
......fbbf......
.......fff......
`;
            case "image29":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image30":return img`
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image31":return img`
..ff.......cc...
..fbff...fcbc...
..fbbcfffbbbc...
...fbbccbbbc....
....fbcbbddc....
.....fbbddc.....
.....fcbfc......
.....fccf.......
....ccccf.......
...cbccccf......
...cdccccf......
..cdbcccccf.....
..cdccccccf.....
.cddccccccf.....
ffddcccbbbcf..ff
fbfdccbbbbbfffbf
fbbfcbbbbbbccbbf
fdbbbbbccbbcbbdc
fbdbbbbbbcbcbddc
.fbbbbbccbbccdc.
.cfc11bbbcbccc..
.c111111bbbcf...
.c111c1ffbbf....
.c11cc1ffbbf....
.c1c1311bbbf....
..f33311bbbf....
..f31c11bbbf....
...fcc11bbbf....
....fc1bbbf.....
.....fbbcbf.....
......fbbf......
.......fff......
`;
            case "image32":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image33":return img`
. . . . . . b b b b . . . . . . 
. . . . b b 3 3 3 3 b b . . . . 
. . . c b 3 3 3 3 1 1 b c . . . 
. . c b 3 3 3 3 3 1 1 1 b c . . 
. c c 1 1 1 3 3 3 3 1 1 3 c c . 
c c d 1 1 1 3 3 3 3 3 3 3 b c c 
c b d d 1 3 3 3 3 3 1 1 1 b b c 
c b b b 3 3 1 1 3 3 1 1 d d b c 
c b b b b d d 1 1 3 b d d d b c 
. c b b b b d d b b b b b b c . 
. . c c b b b b b b b b c c . . 
. . . . c c c c c c c c . . . . 
. . . . . . b 1 1 b . . . . . . 
. . . . . . b 1 1 b b . . . . . 
. . . . . b b d 1 1 b . . . . . 
. . . . . b d d 1 1 b . . . . . 
`;
            case "image34":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image35":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image36":return img`
................
................
................
................
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image37":return img`
................
................
................
................
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image38":return img`
. . . . . . . . . . b 5 b . . . 
. . . . . . . . . b 5 b . . . . 
. . . . . . b b b b b b . . . . 
. . . . . b b 5 5 5 5 5 b . . . 
. . . . b b 5 d 1 f 5 d 4 c . . 
. . . . b 5 5 1 f f d d 4 4 4 b 
. . . . b 5 5 d f b 4 4 4 4 b . 
. . . b d 5 5 5 5 4 4 4 4 b . . 
. . b d d 5 5 5 5 5 5 5 5 b . . 
. b d d d d 5 5 5 5 5 5 5 5 b . 
b d d d b b b 5 5 5 5 5 5 5 b . 
c d d b 5 5 d c 5 5 5 5 5 5 b . 
c b b d 5 d c d 5 5 5 5 5 5 b . 
. b 5 5 b c d d 5 5 5 5 5 d b . 
b b c c c d d d d 5 5 5 b b . . 
. . . c c c c c c c c b b . . . 
`;
            case "image39":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image40":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image41":return img`
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image42":return img`
..ff.......cc...
..fbff...fcbc...
..fbbcfffbbbc...
...fbbccbbbc....
....fbcbbddc....
.....fbbddc.....
.....fcbfc......
.....fccf.......
....ccccf.......
...cbccccf......
...cdccccf......
..cdbcccccf.....
..cdccccccf.....
.cddccccccf.....
ffddcccbbbcf..ff
fbfdccbbbbbfffbf
fbbfcbbbbbbccbbf
fdbbbbbccbbcbbdc
fbdbbbbbbcbcbddc
.fbbbbbccbbccdc.
.cfc11bbbcbccc..
.c111111bbbcf...
.c111c1ffbbf....
.c11cc1ffbbf....
.c1c1311bbbf....
..f33311bbbf....
..f31c11bbbf....
...fcc11bbbf....
....fc1bbbf.....
.....fbbcbf.....
......fbbf......
.......fff......
`;
            case "image43":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image44":return img`
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image45":return img`
..ff.......cc...
..fbff...fcbc...
..fbbcfffbbbc...
...fbbccbbbc....
....fbcbbddc....
.....fbbddc.....
.....fcbfc......
.....fccf.......
....ccccf.......
...cbccccf......
...cdccccf......
..cdbcccccf.....
..cdccccccf.....
.cddccccccf.....
ffddcccbbbcf..ff
fbfdccbbbbbfffbf
fbbfcbbbbbbccbbf
fdbbbbbccbbcbbdc
fbdbbbbbbcbcbddc
.fbbbbbccbbccdc.
.cfc11bbbcbccc..
.c111111bbbcf...
.c111c1ffbbf....
.c11cc1ffbbf....
.c1c1311bbbf....
..f33311bbbf....
..f31c11bbbf....
...fcc11bbbf....
....fc1bbbf.....
.....fbbcbf.....
......fbbf......
.......fff......
`;
            case "image46":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image47":return img`
. . . . . . b b b b . . . . . . 
. . . . b b 3 3 3 3 b b . . . . 
. . . c b 3 3 3 3 1 1 b c . . . 
. . c b 3 3 3 3 3 1 1 1 b c . . 
. c c 1 1 1 3 3 3 3 1 1 3 c c . 
c c d 1 1 1 3 3 3 3 3 3 3 b c c 
c b d d 1 3 3 3 3 3 1 1 1 b b c 
c b b b 3 3 1 1 3 3 1 1 d d b c 
c b b b b d d 1 1 3 b d d d b c 
. c b b b b d d b b b b b b c . 
. . c c b b b b b b b b c c . . 
. . . . c c c c c c c c . . . . 
. . . . . . b 1 1 b . . . . . . 
. . . . . . b 1 1 b b . . . . . 
. . . . . b b d 1 1 b . . . . . 
. . . . . b d d 1 1 b . . . . . 
`;
            case "image48":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image49":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image50":return img`
................
................
................
................
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image51":return img`
................
................
................
................
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image52":return img`
. . . . . . . . . . b 5 b . . . 
. . . . . . . . . b 5 b . . . . 
. . . . . . b b b b b b . . . . 
. . . . . b b 5 5 5 5 5 b . . . 
. . . . b b 5 d 1 f 5 d 4 c . . 
. . . . b 5 5 1 f f d d 4 4 4 b 
. . . . b 5 5 d f b 4 4 4 4 b . 
. . . b d 5 5 5 5 4 4 4 4 b . . 
. . b d d 5 5 5 5 5 5 5 5 b . . 
. b d d d d 5 5 5 5 5 5 5 5 b . 
b d d d b b b 5 5 5 5 5 5 5 b . 
c d d b 5 5 d c 5 5 5 5 5 5 b . 
c b b d 5 d c d 5 5 5 5 5 5 b . 
. b 5 5 b c d d 5 5 5 5 5 d b . 
b b c c c d d d d 5 5 5 b b . . 
. . . c c c c c c c c b b . . . 
`;
            case "image53":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image54":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image55":return img`
. . . . . . b b b b . . . . . . 
. . . . b b 3 3 3 3 b b . . . . 
. . . c b 3 3 3 3 1 1 b c . . . 
. . c b 3 3 3 3 3 1 1 1 b c . . 
. c c 1 1 1 3 3 3 3 1 1 3 c c . 
c c d 1 1 1 3 3 3 3 3 3 3 b c c 
c b d d 1 3 3 3 3 3 1 1 1 b b c 
c b b b 3 3 1 1 3 3 1 1 d d b c 
c b b b b d d 1 1 3 b d d d b c 
. c b b b b d d b b b b b b c . 
. . c c b b b b b b b b c c . . 
. . . . c c c c c c c c . . . . 
. . . . . . b 1 1 b . . . . . . 
. . . . . . b 1 1 b b . . . . . 
. . . . . b b d 1 1 b . . . . . 
. . . . . b d d 1 1 b . . . . . 
`;
            case "image56":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image57":return img`
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image58":return img`
..ff.......cc...
..fbff...fcbc...
..fbbcfffbbbc...
...fbbccbbbc....
....fbcbbddc....
.....fbbddc.....
.....fcbfc......
.....fccf.......
....ccccf.......
...cbccccf......
...cdccccf......
..cdbcccccf.....
..cdccccccf.....
.cddccccccf.....
ffddcccbbbcf..ff
fbfdccbbbbbfffbf
fbbfcbbbbbbccbbf
fdbbbbbccbbcbbdc
fbdbbbbbbcbcbddc
.fbbbbbccbbccdc.
.cfc11bbbcbccc..
.c111111bbbcf...
.c111c1ffbbf....
.c11cc1ffbbf....
.c1c1311bbbf....
..f33311bbbf....
..f31c11bbbf....
...fcc11bbbf....
....fc1bbbf.....
.....fbbcbf.....
......fbbf......
.......fff......
`;
            case "image59":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image60":return img`
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image61":return img`
..ff.......cc...
..fbff...fcbc...
..fbbcfffbbbc...
...fbbccbbbc....
....fbcbbddc....
.....fbbddc.....
.....fcbfc......
.....fccf.......
....ccccf.......
...cbccccf......
...cdccccf......
..cdbcccccf.....
..cdccccccf.....
.cddccccccf.....
ffddcccbbbcf..ff
fbfdccbbbbbfffbf
fbbfcbbbbbbccbbf
fdbbbbbccbbcbbdc
fbdbbbbbbcbcbddc
.fbbbbbccbbccdc.
.cfc11bbbcbccc..
.c111111bbbcf...
.c111c1ffbbf....
.c11cc1ffbbf....
.c1c1311bbbf....
..f33311bbbf....
..f31c11bbbf....
...fcc11bbbf....
....fc1bbbf.....
.....fbbcbf.....
......fbbf......
.......fff......
`;
            case "image62":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image63":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image64":return img`
................
................
................
................
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image65":return img`
................
................
................
................
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image66":return img`
. . . . . . . . . . b 5 b . . . 
. . . . . . . . . b 5 b . . . . 
. . . . . . b b b b b b . . . . 
. . . . . b b 5 5 5 5 5 b . . . 
. . . . b b 5 d 1 f 5 d 4 c . . 
. . . . b 5 5 1 f f d d 4 4 4 b 
. . . . b 5 5 d f b 4 4 4 4 b . 
. . . b d 5 5 5 5 4 4 4 4 b . . 
. . b d d 5 5 5 5 5 5 5 5 b . . 
. b d d d d 5 5 5 5 5 5 5 5 b . 
b d d d b b b 5 5 5 5 5 5 5 b . 
c d d b 5 5 d c 5 5 5 5 5 5 b . 
c b b d 5 d c d 5 5 5 5 5 5 b . 
. b 5 5 b c d d 5 5 5 5 5 d b . 
b b c c c d d d d 5 5 5 b b . . 
. . . c c c c c c c c b b . . . 
`;
            case "image67":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image68":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image69":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image70":return img`
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image71":return img`
..ff.......cc...
..fbff...fcbc...
..fbbcfffbbbc...
...fbbccbbbc....
....fbcbbddc....
.....fbbddc.....
.....fcbfc......
.....fccf.......
....ccccf.......
...cbccccf......
...cdccccf......
..cdbcccccf.....
..cdccccccf.....
.cddccccccf.....
ffddcccbbbcf..ff
fbfdccbbbbbfffbf
fbbfcbbbbbbccbbf
fdbbbbbccbbcbbdc
fbdbbbbbbcbcbddc
.fbbbbbccbbccdc.
.cfc11bbbcbccc..
.c111111bbbcf...
.c111c1ffbbf....
.c11cc1ffbbf....
.c1c1311bbbf....
..f33311bbbf....
..f31c11bbbf....
...fcc11bbbf....
....fc1bbbf.....
.....fbbcbf.....
......fbbf......
.......fff......
`;
            case "image72":return img`
. . . . . . b b b b . . . . . . 
. . . . b b 3 3 3 3 b b . . . . 
. . . c b 3 3 3 3 1 1 b c . . . 
. . c b 3 3 3 3 3 1 1 1 b c . . 
. c c 1 1 1 3 3 3 3 1 1 3 c c . 
c c d 1 1 1 3 3 3 3 3 3 3 b c c 
c b d d 1 3 3 3 3 3 1 1 1 b b c 
c b b b 3 3 1 1 3 3 1 1 d d b c 
c b b b b d d 1 1 3 b d d d b c 
. c b b b b d d b b b b b b c . 
. . c c b b b b b b b b c c . . 
. . . . c c c c c c c c . . . . 
. . . . . . b 1 1 b . . . . . . 
. . . . . . b 1 1 b b . . . . . 
. . . . . b b d 1 1 b . . . . . 
. . . . . b d d 1 1 b . . . . . 
`;
            case "image73":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image74":return img`
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image75":return img`
..ff.......cc...
..fbff...fcbc...
..fbbcfffbbbc...
...fbbccbbbc....
....fbcbbddc....
.....fbbddc.....
.....fcbfc......
.....fccf.......
....ccccf.......
...cbccccf......
...cdccccf......
..cdbcccccf.....
..cdccccccf.....
.cddccccccf.....
ffddcccbbbcf..ff
fbfdccbbbbbfffbf
fbbfcbbbbbbccbbf
fdbbbbbccbbcbbdc
fbdbbbbbbcbcbddc
.fbbbbbccbbccdc.
.cfc11bbbcbccc..
.c111111bbbcf...
.c111c1ffbbf....
.c11cc1ffbbf....
.c1c1311bbbf....
..f33311bbbf....
..f31c11bbbf....
...fcc11bbbf....
....fc1bbbf.....
.....fbbcbf.....
......fbbf......
.......fff......
`;
            case "image76":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image77":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image78":return img`
................
................
................
................
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image79":return img`
................
................
................
................
.......fff......
......fbbf......
.....fbbcbf.....
....fc1bbbf.....
...fcc11bbbf....
..f31c11bbbf....
..f33311bbbf....
.c1c1311bbbf....
.c11cc1ffbbf....
.c111c1ffbbf....
.c111111bbbcf...
.cfc11bbbcbccc..
.fbbbbbccbbccdc.
fbdbbbbbbcbcbddc
fdbbbbbccbbcbbdc
fbbfcbbbbbbccbbf
fbfdccbbbbbfffbf
ffddcccbbbcf..ff
.cddccccccf.....
..cdccccccf.....
..cdbcccccf.....
...cdccccf......
...cbccccf......
....ccccf.......
.....fccf.......
.....fcbfc......
.....fbbddc.....
....fbcbbddc....
...fbbccbbbc....
..fbbcfffbbbc...
..fbff...fcbc...
..ff.......cc...
`;
            case "image80":return img`
. . . . . . . . . . b 5 b . . . 
. . . . . . . . . b 5 b . . . . 
. . . . . . b b b b b b . . . . 
. . . . . b b 5 5 5 5 5 b . . . 
. . . . b b 5 d 1 f 5 d 4 c . . 
. . . . b 5 5 1 f f d d 4 4 4 b 
. . . . b 5 5 d f b 4 4 4 4 b . 
. . . b d 5 5 5 5 4 4 4 4 b . . 
. . b d d 5 5 5 5 5 5 5 5 b . . 
. b d d d d 5 5 5 5 5 5 5 5 b . 
b d d d b b b 5 5 5 5 5 5 5 b . 
c d d b 5 5 d c 5 5 5 5 5 5 b . 
c b b d 5 d c d 5 5 5 5 5 5 b . 
. b 5 5 b c d d 5 5 5 5 5 d b . 
b b c c c d d d d 5 5 5 b b . . 
. . . c c c c c c c c b b . . . 
`;
            case "image81":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image82":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . 1 3 3 3 3 3 1 . . . . . 
. . . . . 1 1 1 1 1 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "walkRight":
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . f f e e e e f 2 f . . . . 
. . f f e e e e f 2 2 2 f . . . 
. . f e e e f f e e e e f . . . 
. . f f f f e e 2 2 2 2 e f . . 
. . f e 2 2 2 f f f f e 2 f . . 
. f f f f f f f e e e f f f . . 
. f f e 4 4 e b f 4 4 e e f . . 
. f e e 4 d 4 1 f d d e f . . . 
. . f e e e e e d d d f . . . . 
. . . . f 4 d d e 4 e f . . . . 
. . . . f e d d e 2 2 f . . . . 
. . . f f f e e f 5 5 f f . . . 
. . . f f f f f f f f f f . . . 
. . . . f f . . . f f f . . . . 
`, img`
. . . . . f f f f f f . . . . . 
. . . f f e e e e f 2 f . . . . 
. . f f e e e e f 2 2 2 f . . . 
. . f e e e f f e e e e f . . . 
. . f f f f e e 2 2 2 2 e f . . 
. . f e 2 2 2 f f f f e 2 f . . 
. f f f f f f f e e e f f f . . 
. f f e 4 4 e b f 4 4 e e f . . 
. f e e 4 d 4 1 f d d e f f . . 
. . f e e e 4 d d d d f d d f . 
. . . f f e e 4 e e e f b b f . 
. . . . f 2 2 2 4 d d e b b f . 
. . . . e 2 2 2 e d d e b f . . 
. . . . f 4 4 4 f e e f f . . . 
. . . . . f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . f f e e e e f 2 f . . . . 
. . f f e e e e f 2 2 2 f . . . 
. . f e e e f f e e e e f . . . 
. . f f f f e e 2 2 2 2 e f . . 
. . f e 2 2 2 f f f f e 2 f . . 
. f f f f f f f e e e f f f . . 
. f f e 4 4 e b f 4 4 e e f . . 
. f e e 4 d 4 1 f d d e f . . . 
. . f e e e e e d d d f . . . . 
. . . . f 4 d d e 4 e f . . . . 
. . . . f e d d e 2 2 f . . . . 
. . . f f f e e f 5 5 f f . . . 
. . . f f f f f f f f f f . . . 
. . . . f f . . . f f f . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . f f e e e e f 2 f . . . . 
. . f f e e e e f 2 2 2 f . . . 
. . f e e e f f e e e e f . . . 
. . f f f f e e 2 2 2 2 e f . . 
. . f e 2 2 2 f f f f e 2 f . . 
. f f f f f f f e e e f f f . . 
. f f e 4 4 e b f 4 4 e e f . . 
. f e e 4 d 4 1 f d d e f f . . 
. . f e e e 4 d d d d f d d f . 
. . . . f e e 4 e e e f b b f . 
. . . . f 2 2 2 4 d d e b b f . 
. . . f f 4 4 4 e d d e b f . . 
. . . f f f f f f e e f f . . . 
. . . . f f . . . f f f . . . . 
`];
            case "walkLeft":
            case "anim2":return [img`
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e e f f . . . . 
. . . f 2 2 2 e d d 4 . . . . . 
. . . f 2 2 2 e d d e . . . . . 
. . . f 5 5 4 f e e f . . . . . 
. . . . f f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d e e e e e f . . . 
. . . f e 4 e d d 4 f . . . . . 
. . . f 2 2 e d d e f . . . . . 
. . f f 5 5 f e e f f f . . . . 
. . f f f f f f f f f f . . . . 
. . . f f f . . . f f . . . . . 
`, img`
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e e f f . . . . 
. . . f 2 2 2 e d d 4 . . . . . 
. . . f 2 2 2 e d d e . . . . . 
. . . f 5 5 4 f e e f . . . . . 
. . . . f f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e d d 4 . . . . 
. . . f 2 2 2 2 e d d e . . . . 
. . f f 5 5 4 4 f e e f . . . . 
. . f f f f f f f f f f . . . . 
. . . f f f . . . f f . . . . . 
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
