controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (bullets > 0) {
        projectile = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . 1 1 1 1 1 . . . . . . 
            . . . . 1 3 3 3 3 3 1 . . . . . 
            . . . . 1 3 3 3 3 3 1 . . . . . 
            . . . . 1 3 3 3 3 3 1 . . . . . 
            . . . . 1 3 3 3 3 3 1 . . . . . 
            . . . . 1 3 3 3 3 3 1 . . . . . 
            . . . . . 1 1 1 1 1 . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, dude, bulletV, 0)
        projectile.setFlag(SpriteFlag.AutoDestroy, true)
        bullets += -1
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile`, function (sprite, location) {
    info.changeLifeBy(-1)
    dude.setPosition(21, 87)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (dude.vy == 0) {
        dude.vy = -180
    }
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    bulletV = -200
    animation.runImageAnimation(
    dude,
    assets.animation`walkLeft`,
    100,
    true
    )
})
function cleanup () {
    enemies = sprites.allOfKind(SpriteKind.Enemy)
    for (let value of enemies) {
        value.destroy()
    }
    for (let ff of sprites.allOfKind(SpriteKind.Food)) {
        ff.destroy()
    }
}
scene.onOverlapTile(SpriteKind.Enemy, assets.tile`myTile`, function (sprite, location) {
    sprite.destroy()
    ghosties += -1
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    bulletV = 200
    animation.runImageAnimation(
    dude,
    assets.animation`walkRight`,
    100,
    true
    )
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    bullets += 3
    otherSprite.destroy()
})
function genGhostys () {
    ghosty = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    ghosty.setPosition(200, 0)
    ghosty.ay = 350
    ghosty.vx = 100
    ghosties += 1
}
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeScoreBy(2)
    otherSprite.destroy()
    if (otherSprite == ghosty) {
        ghosties += -1
    }
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleInsignia, function (sprite, location) {
    // for (let index = 0; index < 5; index++) {
    // pubullet = sprites.create(img`
    // . . . . . . . . . . . . . . . .
    // . . . . . . . . . . . . . . . .
    // . . . . . . . . . . . . . . . .
    // . . . . . . . . . . . . . . . .
    // . . . . . . . . . . . . . . . .
    // . . . . . 1 1 1 1 1 . . . . . .
    // . . . . 1 3 3 3 3 3 1 . . . . .
    // . . . . 1 3 3 3 3 3 1 . . . . .
    // . . . . 1 3 3 3 3 3 1 . . . . .
    // . . . . 1 3 3 3 3 3 1 . . . . .
    // . . . . 1 3 3 3 3 3 1 . . . . .
    // . . . . . 1 1 1 1 1 . . . . . .
    // . . . . . . . . . . . . . . . .
    // . . . . . . . . . . . . . . . .
    // . . . . . . . . . . . . . . . .
    // . . . . . . . . . . . . . . . .
    // `, SpriteKind.Food)
    // pubullet.setPosition(randint(0, 16 * 16), randint(0, 16 * 16))
    // pubullet.ay = gravity
    // }
    if (level == 1) {
        game.over(true)
    } else {
        tiles.setTilemap(tilemap`level2`)
        dude.setPosition(40, 230)
        info.changeScoreBy(10)
        level += 1
        cleanup()
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    if (level == 1) {
        dude.setPosition(40, 210)
    } else {
        dude.setPosition(21, 0)
    }
})
let level = 0
let ghosty: Sprite = null
let ghosties = 0
let enemies: Sprite[] = []
let projectile: Sprite = null
let dude: Sprite = null
let bulletV = 0
let bullets = 0
game.splash("Use Arrow keys to move left and right", "Space to jump and x to shoot")
let endlevel = 2
bullets = 3
let gravity = 350
bulletV = 200
info.setScore(0)
scene.setBackgroundColor(9)
info.setLife(3)
tiles.setTilemap(tilemap`level1`)
dude = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
dude.setPosition(21, 216)
scene.cameraFollowSprite(dude)
controller.moveSprite(dude, 100, 0)
dude.ay = gravity
let Sharky = sprites.create(img`
    ................
    ................
    ................
    ................
    .......fff......
    ......fbbf......
    .....fbbcbf.....
    ....fc1bbbf.....
    ...fcc11bbbf....
    ..f31c11bbbf....
    ..f33311bbbf....
    .c1c1311bbbf....
    .c11cc1ffbbf....
    .c111c1ffbbf....
    .c111111bbbcf...
    .cfc11bbbcbccc..
    .fbbbbbccbbccdc.
    fbdbbbbbbcbcbddc
    fdbbbbbccbbcbbdc
    fbbfcbbbbbbccbbf
    fbfdccbbbbbfffbf
    ffddcccbbbcf..ff
    .cddccccccf.....
    ..cdccccccf.....
    ..cdbcccccf.....
    ...cdccccf......
    ...cbccccf......
    ....ccccf.......
    .....fccf.......
    .....fcbfc......
    .....fbbddc.....
    ....fbcbbddc....
    ...fbbccbbbc....
    ..fbbcfffbbbc...
    ..fbff...fcbc...
    ..ff.......cc...
    `, SpriteKind.Enemy)
Sharky.setPosition(345, 150)
Sharky.setBounceOnWall(true)
Sharky.ay = gravity
let Sharky1 = sprites.create(img`
    ................
    ................
    ................
    ................
    .......fff......
    ......fbbf......
    .....fbbcbf.....
    ....fc1bbbf.....
    ...fcc11bbbf....
    ..f31c11bbbf....
    ..f33311bbbf....
    .c1c1311bbbf....
    .c11cc1ffbbf....
    .c111c1ffbbf....
    .c111111bbbcf...
    .cfc11bbbcbccc..
    .fbbbbbccbbccdc.
    fbdbbbbbbcbcbddc
    fdbbbbbccbbcbbdc
    fbbfcbbbbbbccbbf
    fbfdccbbbbbfffbf
    ffddcccbbbcf..ff
    .cddccccccf.....
    ..cdccccccf.....
    ..cdbcccccf.....
    ...cdccccf......
    ...cbccccf......
    ....ccccf.......
    .....fccf.......
    .....fcbfc......
    .....fbbddc.....
    ....fbcbbddc....
    ...fbbccbbbc....
    ..fbbcfffbbbc...
    ..fbff...fcbc...
    ..ff.......cc...
    `, SpriteKind.Enemy)
Sharky1.setPosition(360, 150)
Sharky1.setBounceOnWall(true)
let Ducky = sprites.create(img`
    . . . . . . . . . . b 5 b . . . 
    . . . . . . . . . b 5 b . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . . . . b b 5 d 1 f 5 d 4 c . . 
    . . . . b 5 5 1 f f d d 4 4 4 b 
    . . . . b 5 5 d f b 4 4 4 4 b . 
    . . . b d 5 5 5 5 4 4 4 4 b . . 
    . . b d d 5 5 5 5 5 5 5 5 b . . 
    . b d d d d 5 5 5 5 5 5 5 5 b . 
    b d d d b b b 5 5 5 5 5 5 5 b . 
    c d d b 5 5 d c 5 5 5 5 5 5 b . 
    c b b d 5 d c d 5 5 5 5 5 5 b . 
    . b 5 5 b c d d 5 5 5 5 5 d b . 
    b b c c c d d d d 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `, SpriteKind.Enemy)
Ducky.setPosition(455, 240)
Ducky.setBounceOnWall(true)
Ducky.vx = 100
Ducky.ay = gravity
let pubullet = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . 1 1 1 1 1 . . . . . . 
    . . . . 1 3 3 3 3 3 1 . . . . . 
    . . . . 1 3 3 3 3 3 1 . . . . . 
    . . . . 1 3 3 3 3 3 1 . . . . . 
    . . . . 1 3 3 3 3 3 1 . . . . . 
    . . . . 1 3 3 3 3 3 1 . . . . . 
    . . . . . 1 1 1 1 1 . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Food)
pubullet.setPosition(32, 100)
pubullet.ay = gravity
for (let index = 0; index < 5; index++) {
    pubullet = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 1 1 1 1 1 . . . . . . 
        . . . . 1 3 3 3 3 3 1 . . . . . 
        . . . . 1 3 3 3 3 3 1 . . . . . 
        . . . . 1 3 3 3 3 3 1 . . . . . 
        . . . . 1 3 3 3 3 3 1 . . . . . 
        . . . . 1 3 3 3 3 3 1 . . . . . 
        . . . . . 1 1 1 1 1 . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Food)
    pubullet.setPosition(randint(0, 64 * 16), randint(0, 16 * 16))
    pubullet.ay = gravity
}
game.onUpdate(function () {
    if (Sharky.vy <= 0) {
        Sharky.setImage(img`
            .......fff......
            ......fbbf......
            .....fbbcbf.....
            ....fc1bbbf.....
            ...fcc11bbbf....
            ..f31c11bbbf....
            ..f33311bbbf....
            .c1c1311bbbf....
            .c11cc1ffbbf....
            .c111c1ffbbf....
            .c111111bbbcf...
            .cfc11bbbcbccc..
            .fbbbbbccbbccdc.
            fbdbbbbbbcbcbddc
            fdbbbbbccbbcbbdc
            fbbfcbbbbbbccbbf
            fbfdccbbbbbfffbf
            ffddcccbbbcf..ff
            .cddccccccf.....
            ..cdccccccf.....
            ..cdbcccccf.....
            ...cdccccf......
            ...cbccccf......
            ....ccccf.......
            .....fccf.......
            .....fcbfc......
            .....fbbddc.....
            ....fbcbbddc....
            ...fbbccbbbc....
            ..fbbcfffbbbc...
            ..fbff...fcbc...
            ..ff.......cc...
            `)
    } else {
        Sharky.setImage(img`
            ..ff.......cc...
            ..fbff...fcbc...
            ..fbbcfffbbbc...
            ...fbbccbbbc....
            ....fbcbbddc....
            .....fbbddc.....
            .....fcbfc......
            .....fccf.......
            ....ccccf.......
            ...cbccccf......
            ...cdccccf......
            ..cdbcccccf.....
            ..cdccccccf.....
            .cddccccccf.....
            ffddcccbbbcf..ff
            fbfdccbbbbbfffbf
            fbbfcbbbbbbccbbf
            fdbbbbbccbbcbbdc
            fbdbbbbbbcbcbddc
            .fbbbbbccbbccdc.
            .cfc11bbbcbccc..
            .c111111bbbcf...
            .c111c1ffbbf....
            .c11cc1ffbbf....
            .c1c1311bbbf....
            ..f33311bbbf....
            ..f31c11bbbf....
            ...fcc11bbbf....
            ....fc1bbbf.....
            .....fbbcbf.....
            ......fbbf......
            .......fff......
            `)
    }
    if (Sharky1.vy <= 0) {
        Sharky1.setImage(img`
            .......fff......
            ......fbbf......
            .....fbbcbf.....
            ....fc1bbbf.....
            ...fcc11bbbf....
            ..f31c11bbbf....
            ..f33311bbbf....
            .c1c1311bbbf....
            .c11cc1ffbbf....
            .c111c1ffbbf....
            .c111111bbbcf...
            .cfc11bbbcbccc..
            .fbbbbbccbbccdc.
            fbdbbbbbbcbcbddc
            fdbbbbbccbbcbbdc
            fbbfcbbbbbbccbbf
            fbfdccbbbbbfffbf
            ffddcccbbbcf..ff
            .cddccccccf.....
            ..cdccccccf.....
            ..cdbcccccf.....
            ...cdccccf......
            ...cbccccf......
            ....ccccf.......
            .....fccf.......
            .....fcbfc......
            .....fbbddc.....
            ....fbcbbddc....
            ...fbbccbbbc....
            ..fbbcfffbbbc...
            ..fbff...fcbc...
            ..ff.......cc...
            `)
    } else {
        Sharky1.setImage(img`
            ..ff.......cc...
            ..fbff...fcbc...
            ..fbbcfffbbbc...
            ...fbbccbbbc....
            ....fbcbbddc....
            .....fbbddc.....
            .....fcbfc......
            .....fccf.......
            ....ccccf.......
            ...cbccccf......
            ...cdccccf......
            ..cdbcccccf.....
            ..cdccccccf.....
            .cddccccccf.....
            ffddcccbbbcf..ff
            fbfdccbbbbbfffbf
            fbbfcbbbbbbccbbf
            fdbbbbbccbbcbbdc
            fbdbbbbbbcbcbddc
            .fbbbbbccbbccdc.
            .cfc11bbbcbccc..
            .c111111bbbcf...
            .c111c1ffbbf....
            .c11cc1ffbbf....
            .c1c1311bbbf....
            ..f33311bbbf....
            ..f31c11bbbf....
            ...fcc11bbbf....
            ....fc1bbbf.....
            .....fbbcbf.....
            ......fbbf......
            .......fff......
            `)
    }
    if (game.runtime() <= 100) {
        Sharky1.ay = 350
    }
    if (dude.vx == 0) {
        dude.setImage(img`
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 1 f d d f 1 4 e e f . 
            . . f e e d d d d d d e e f . . 
            . . . f e e 4 4 4 4 e e f . . . 
            . . e 4 f 2 2 2 2 2 2 f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . . 
            `)
    }
    if (level == 1) {
        if (ghosties == 0) {
            genGhostys()
        } else {
            if (ghosty.x < 16) {
                ghosty.vx = 100
            }
            if (ghosty.x > 240) {
                ghosty.vx = -100
            }
            if (ghosty.vx == 0) {
                ghosty.vx = 100
            }
        }
    }
})
